#!/usr/bin/env bash
# docucentral-smoke-test.sh — Post-deploy verification against a running Nuxeo.
#
# Walks a throwaway document through the full lifecycle
# (create -> submit -> approve -> publish) and asserts the server-side
# behaviour: reference generation, state transitions, audit fields, versioning.
# Cleans up after itself.
#
# Usage:
#   ./scripts/docucentral-smoke-test.sh
#   ./scripts/docucentral-smoke-test.sh --keep    leave the test document behind

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_DIR/config/nuxeo-local.properties"

# shellcheck disable=SC1090
source <(grep -v '^#' "$CONFIG_FILE" | grep -v '^$')

API="$NUXEO_URL/api/v1"
AUTH=(-u "$NUXEO_ADMIN_USER:$NUXEO_ADMIN_PASSWORD")
JSON=(-H "Content-Type: application/json")
PARENT="/default-domain/workspaces/docucentral/proc"
DOC_NAME="smoke-test-$(date +%s)"

PASS=0
FAIL=0
DOC_UID=""

ok()  { printf "  [ok]   %s\n" "$1"; PASS=$((PASS + 1)); }
bad() { printf "  [FAIL] %s\n" "$1"; FAIL=$((FAIL + 1)); }

# body <path> — GET and echo the JSON body
body() { curl -s "$API$1" "${AUTH[@]}" --max-time 30; }

# jq_get <json> <filter>
jqv() { echo "$1" | jq -r "$2" 2>/dev/null; }

cleanup() {
  if [[ -n "$DOC_UID" && "${1:-}" != "--keep" ]]; then
    curl -s -o /dev/null -X DELETE "$API/id/$DOC_UID" "${AUTH[@]}" --max-time 30
    echo ""
    echo "Test document removed."
  fi
}
trap 'cleanup "${1:-}"' EXIT

echo "================================================================"
echo " DocuCentral — smoke test against $NUXEO_URL"
echo "================================================================"

command -v jq >/dev/null 2>&1 || { echo "jq is required for this script."; exit 1; }

# ── 1. Platform reachable ────────────────────────────────────────────────────
echo ""
echo "[1/6] Platform"
LOGIN=$(curl -s -o /dev/null -w "%{http_code}" "$API/automation/login" "${AUTH[@]}" --max-time 10)
if [[ "$LOGIN" == "200" ]]; then
  ok "server reachable and credentials valid"
else
  bad "server returned HTTP $LOGIN for $API/automation/login"
  echo ""
  echo "Aborting: the server must be running before the smoke test can run."
  exit 1
fi

# ── 2. Content model registered ──────────────────────────────────────────────
echo ""
echo "[2/6] Content model"
for type in DCControlledDocument DCLibrary; do
  if [[ "$(curl -s -o /dev/null -w "%{http_code}" "$API/config/types/$type" "${AUTH[@]}")" == "200" ]]; then
    ok "document type $type registered"
  else
    bad "document type $type NOT registered"
  fi
done

for vocab in dc_department dc_docclass dc_confidentiality; do
  entries=$(jqv "$(body "/directory/$vocab")" '.entries | length')
  if [[ "${entries:-0}" -gt 0 ]]; then
    ok "vocabulary $vocab loaded ($entries entries)"
  else
    bad "vocabulary $vocab is empty or missing"
  fi
done

# ── 3. Create + reference generation ─────────────────────────────────────────
echo ""
echo "[3/6] Create"
CREATE=$(curl -s -X POST "$API/path$PARENT" "${AUTH[@]}" "${JSON[@]}" --max-time 30 -d "{
  \"entity-type\": \"document\",
  \"name\": \"$DOC_NAME\",
  \"type\": \"DCControlledDocument\",
  \"properties\": {
    \"dc:title\": \"Smoke test document\",
    \"dcx:department\": \"PROC\",
    \"dcx:documentClass\": \"PROCEDURE\"
  }
}")
DOC_UID=$(jqv "$CREATE" '.uid')

if [[ -n "$DOC_UID" && "$DOC_UID" != "null" ]]; then
  ok "document created ($DOC_UID)"
else
  bad "creation failed: $(echo "$CREATE" | head -c 300)"
  echo ""
  echo "Aborting: nothing to run the lifecycle against."
  exit 1
fi

REFERENCE=$(jqv "$(body "/id/$DOC_UID?properties=docucentral")" '.properties."dcx:reference"')
if [[ "$REFERENCE" =~ ^DC-PROC-[0-9]{4}-[0-9]{4}$ ]]; then
  ok "reference auto-assigned: $REFERENCE"
else
  bad "reference not generated by the aboutToCreate handler (got: $REFERENCE)"
fi

STATE=$(jqv "$(body "/id/$DOC_UID")" '.state')
if [[ "$STATE" == "draft" ]]; then
  ok "initial lifecycle state is draft"
else
  bad "initial state is '$STATE', expected 'draft'"
fi

# run_op <operation-id> <params-json>
run_op() {
  curl -s -X POST "$API/automation/$1" "${AUTH[@]}" "${JSON[@]}" --max-time 30 \
    -d "{\"input\":\"doc:$DOC_UID\",\"params\":$2}"
}

# ── 4. Submit for review ─────────────────────────────────────────────────────
echo ""
echo "[4/6] Submit for review"
run_op "javascript.docucentral_SubmitForReview" '{}' > /dev/null
DOC=$(body "/id/$DOC_UID?properties=docucentral")
if [[ "$(jqv "$DOC" '.state')" == "review" ]]; then
  ok "state moved to review"
else
  bad "state is '$(jqv "$DOC" '.state')', expected 'review'"
fi
if [[ "$(jqv "$DOC" '.properties."dcx:submittedBy"')" == "$NUXEO_ADMIN_USER" ]]; then
  ok "submittedBy recorded"
else
  bad "submittedBy not recorded"
fi

# ── 5. Approve ───────────────────────────────────────────────────────────────
echo ""
echo "[5/6] Approve"
run_op "javascript.docucentral_Approve" '{"comment":"smoke test"}' > /dev/null
DOC=$(body "/id/$DOC_UID?properties=docucentral")
if [[ "$(jqv "$DOC" '.state')" == "approved" ]]; then
  ok "state moved to approved"
else
  bad "state is '$(jqv "$DOC" '.state')', expected 'approved'"
fi
if [[ "$(jqv "$DOC" '.properties."dcx:approvedBy"')" == "$NUXEO_ADMIN_USER" ]]; then
  ok "approvedBy recorded"
else
  bad "approvedBy not recorded"
fi

# ── 6. Publish ───────────────────────────────────────────────────────────────
echo ""
echo "[6/6] Publish"
run_op "javascript.docucentral_Publish" '{"reviewCycleMonths":12}' > /dev/null
DOC=$(body "/id/$DOC_UID?properties=docucentral,uid")
if [[ "$(jqv "$DOC" '.state')" == "published" ]]; then
  ok "state moved to published"
else
  bad "state is '$(jqv "$DOC" '.state')', expected 'published'"
fi

NEXT_REVIEW=$(jqv "$DOC" '.properties."dcx:nextReviewDate"')
if [[ -n "$NEXT_REVIEW" && "$NEXT_REVIEW" != "null" ]]; then
  ok "next review date scheduled: ${NEXT_REVIEW%%T*}"
else
  bad "next review date was not set"
fi

MAJOR=$(jqv "$DOC" '.properties."uid:major_version"')
if [[ "${MAJOR:-0}" -ge 1 ]]; then
  ok "major version snapshot created (v$MAJOR)"
else
  bad "no major version was created on publish"
fi

# Guard rail: publishing twice must be refused.
ERR=$(run_op "javascript.docucentral_Publish" '{}')
if echo "$ERR" | grep -q "Only an approved document"; then
  ok "guard rail rejects publishing a published document"
else
  bad "guard rail did not reject a second publish"
fi

echo ""
echo "================================================================"
printf " Result: %d passed, %d failed\n" "$PASS" "$FAIL"
echo "================================================================"
[[ "$FAIL" -eq 0 ]] || exit 1
